service: youngmonkey-sls
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: v1
  memorySize: 128
  profile: ym

functions:
  placeOrder:
    handler: src/application/infra/sls/http/functions/placeOrder.handle
    events:
      - http:
          path: /orders
          method: post
          cors: true
